version: '3.9'

services:
  backend:
    ports:
      - "8001:8001"
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/backend
    build: ./backend
    environment:
      - DB_URL=http://db:8002
    
  db:
    ports:
      - "8002:8002"
    volumes:
      - ./db:/usr/src/db
    build: ./db
  
  frontend:
    build: ./frontend
    ports:
      - '8000:8000'
    volumes:
      - ./frontend:/usr/src/frontend
    depends_on:
      - backend
    environment:
      - BACKEND_URL=https://backend:8001
    
    

